import type { Modality, SubjectSchedule } from '@schooler/shared';
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';

export interface ScheduleValues { weekday: number; start_time: string; end_time: string; modality: Modality; classroom: string; }
export function ScheduleForm({ schedule, busy, onSubmit, onCancel }: { schedule?: SubjectSchedule; busy: boolean; onSubmit: (values: ScheduleValues) => void; onCancel: () => void }) {
  const [values, setValues] = useState<ScheduleValues>({ weekday: schedule?.weekday ?? 1, start_time: schedule?.start_time.slice(0, 5) ?? '08:00', end_time: schedule?.end_time.slice(0, 5) ?? '10:00', modality: schedule?.modality ?? 'virtual', classroom: schedule?.classroom ?? '' });
  const valid = values.end_time > values.start_time;
  const field = <K extends keyof ScheduleValues>(key: K, value: ScheduleValues[K]) => setValues((current) => ({ ...current, [key]: value }));
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); if (valid) onSubmit(values); }}><label className="text-sm font-medium">Día<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" value={values.weekday} onChange={(event) => field('weekday', Number(event.target.value))}>{['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((day, index) => <option key={day} value={index + 1}>{day}</option>)}</select></label><label className="text-sm font-medium">Modalidad<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" value={values.modality} onChange={(event) => field('modality', event.target.value as Modality)}><option value="virtual">Virtual</option><option value="presencial">Presencial</option></select></label><label className="text-sm font-medium">Inicio<Input className="mt-2" type="time" value={values.start_time} onChange={(event) => field('start_time', event.target.value)} /></label><label className="text-sm font-medium">Final<Input className="mt-2" type="time" value={values.end_time} onChange={(event) => field('end_time', event.target.value)} /></label><label className="text-sm font-medium sm:col-span-2">Aula (opcional)<Input className="mt-2" value={values.classroom} onChange={(event) => field('classroom', event.target.value)} /></label>{!valid && <p className="text-sm text-rose-400 sm:col-span-2">La hora final debe ser posterior a la inicial.</p>}<div className="flex gap-2 sm:col-span-2"><Button disabled={busy || !valid}>{busy ? 'Guardando…' : 'Guardar horario'}</Button><Button type="button" className="bg-zinc-800 text-zinc-100 hover:bg-zinc-700" onClick={onCancel}>Cancelar</Button></div></form>;
}
