import { zodResolver } from '@hookform/resolvers/zod';
import type { Activity, Subject } from '@schooler/shared';
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';

const schema = z.object({ subject_id: z.string().min(1, 'Selecciona una materia.'), title: z.string().trim().min(1, 'El título es obligatorio.').max(160), description: z.string(), personal_notes: z.string(), due_date: z.string().min(1), due_time: z.string(), type: z.enum(['TASK','EXAM','QUIZ','PROJECT','STUDY']), status: z.enum(['PENDING','IN_PROGRESS','COMPLETED','CANCELLED']), importance: z.enum(['LOW','MEDIUM','HIGH']), percentage: z.string(), grade: z.string() });
type FormValues = z.infer<typeof schema>;
export type ActivityPayload = Omit<FormValues, 'percentage' | 'grade'> & { percentage: number | null; grade: number | null };

export function ActivityForm({ subjects, activity, defaultSubjectId, busy, onSubmit, onCancel }: { subjects: Subject[]; activity?: Activity; defaultSubjectId?: string; busy: boolean; onSubmit: (payload: ActivityPayload) => void; onCancel: () => void }) {
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { subject_id: activity?.subject_id ?? defaultSubjectId ?? subjects[0]?.id ?? '', title: activity?.title ?? '', description: activity?.description ?? '', personal_notes: activity?.personal_notes ?? '', due_date: activity?.due_date ?? new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Bogota', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()), due_time: activity?.due_time?.slice(0,5) ?? '', type: activity?.type ?? 'TASK', status: activity?.status === 'OVERDUE' ? 'PENDING' : activity?.status ?? 'PENDING', importance: activity?.importance ?? 'MEDIUM', percentage: activity?.percentage?.toString() ?? '', grade: activity?.grade?.toString() ?? '' } });
  const type = watch('type');
  useEffect(() => { if (type === 'STUDY') { setValue('percentage', ''); setValue('grade', ''); } else if (type === 'EXAM' && !activity) setValue('percentage', '20'); }, [type, setValue, activity]);
  const submit = handleSubmit((values) => onSubmit({ ...values, percentage: values.percentage === '' ? null : Number(values.percentage), grade: values.grade === '' ? null : Number(values.grade) }));
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><label className="text-sm font-medium">Materia<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" {...register('subject_id')}>{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label className="text-sm font-medium">Tipo<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" {...register('type')}><option value="TASK">Tarea</option><option value="EXAM">Parcial</option><option value="QUIZ">Quiz</option><option value="PROJECT">Proyecto</option><option value="STUDY">Estudio</option></select></label><label className="text-sm font-medium sm:col-span-2">Título<Input className="mt-2" {...register('title')} /></label>{errors.title && <p className="text-sm text-rose-400 sm:col-span-2">{errors.title.message}</p>}<label className="text-sm font-medium sm:col-span-2">Descripción (opcional)<textarea className="mt-2 min-h-24 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3" {...register('description')} /></label><label className="text-sm font-medium">Fecha límite<Input className="mt-2" type="date" {...register('due_date')} /></label><label className="text-sm font-medium">Hora (opcional)<Input className="mt-2" type="time" {...register('due_time')} /></label><label className="text-sm font-medium">Estado<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" {...register('status')}><option value="PENDING">Pendiente</option><option value="IN_PROGRESS">En progreso</option><option value="COMPLETED">Completada</option><option value="CANCELLED">Cancelada</option></select></label><label className="text-sm font-medium">Importancia<select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3" {...register('importance')}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option></select></label>{type !== 'STUDY' && <><label className="text-sm font-medium">Porcentaje (opcional)<Input className="mt-2" type="number" min="0.01" max="100" step="0.01" {...register('percentage')} /></label><label className="text-sm font-medium">Nota (opcional)<Input className="mt-2" type="number" min="0" max="5" step="0.01" {...register('grade')} /></label></>}<label className="text-sm font-medium sm:col-span-2">Notas personales (opcional)<textarea className="mt-2 min-h-20 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3" {...register('personal_notes')} /></label><div className="flex gap-2 sm:col-span-2"><Button disabled={busy}>{busy ? 'Guardando…' : activity ? 'Guardar cambios' : 'Crear actividad'}</Button><Button type="button" className="bg-zinc-800 text-zinc-100 hover:bg-zinc-700" onClick={onCancel}>Cancelar</Button></div></form>;
}
