import cors from 'cors';
import express from 'express';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/errors.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { healthRouter } from './modules/health/health.routes.js';
import { academicPeriodsRouter } from './modules/academic-periods/academic-periods.routes.js';
import { schedulesRouter } from './modules/schedules/schedules.routes.js';
import { subjectsRouter } from './modules/subjects/subjects.routes.js';
import { activitiesRouter } from './modules/activities/activities.routes.js';
import { dashboardRouter } from './modules/dashboard/dashboard.routes.js';
import { calendarRouter } from './modules/calendar/calendar.routes.js';
import { notificationsRouter } from './modules/notifications/notifications.routes.js';
import { notificationProcessorRouter } from './modules/notifications/notification-processor.routes.js';

export const app = express();
app.disable('x-powered-by');
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'no-referrer');
  res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  next();
});
app.use(cors({ origin: env.WEB_URL }));
app.use(express.json({ limit: '100kb' }));
app.use('/health', healthRouter);
app.use('/api/auth', authRouter);
app.use('/api/academic-periods', academicPeriodsRouter);
app.use('/api/subjects', subjectsRouter);
app.use('/api/schedules', schedulesRouter);
app.use('/api/activities', activitiesRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/calendar', calendarRouter);
app.use('/api/notifications', notificationsRouter);
app.use('/api/internal/process-notifications', notificationProcessorRouter);
app.use(notFound);
app.use(errorHandler);

export default app;
